### ISSUE TITLE
Slack alert translation

### ISSUE THREAD

**Issue by VincentCATILLON** [rubenmak/PokemonGo-SlackBot#14]
Slack alerts don't use the locale as the name does.

**Comment by rubenmak** [comment]
Hi Vincent, since Pokevision is down, I changed the text. Since you're the expert, could you check whether my translation to French and German makes sense? ;): 

https://github.com/rubenmak/PokemonGo-SlackBot/blob/develop/locales/translations.de.json
https://github.com/rubenmak/PokemonGo-SlackBot/blob/develop/locales/translations.fr.json

**Comment by VincentCATILLON** [comment]
Hi Ruben,

Of course i did it, and everything seems to be right :)
